name: safe_transfer
publish_to: "none" # Remove this line if you wish to publish to pub.dev
description: 安全转账
# The following line prevents the package from being accidentally published to
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  camera: 0.10.5+9
  cloud_firestore: ^4.15.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_ui_auth: ^1.13.1
  flutter:
    sdk: flutter
  flutter_scankit: 2.0.3
  google_mlkit_text_recognition: 0.11.0
  intl: any
  logger: 2.0.2+1
  qr_flutter: 4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: SmileySans
      fonts:
        - asset: assets/fonts/SmileySans-Oblique.ttf
  #        - asset: fonts/Schyler-Italic.ttf
  #          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
