name: safe_transfer
publish_to: "none" # Remove this line if you wish to publish to pub.dev
description: 安全转账
# The following line prevents the package from being accidentally published to
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.0
  cloud_firestore: ^4.15.6
  cloud_functions: ^4.6.7
  cunning_document_scanner: ^1.2.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  equatable: ^2.0.5
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_ui_auth: ^1.13.1
  firebase_ui_firestore: ^1.6.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  google_mlkit_barcode_scanning: ^0.10.0
  google_mlkit_text_recognition: ^0.11.0
  intl: any
  intl_phone_field: ^3.2.0
  local_auth: ^2.2.0
  logger: 2.0.2+1
  pinput: ^4.0.0
  pretty_qr_code: ^3.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: SmileySans
      fonts:
        - asset: assets/fonts/SmileySans-Oblique.ttf
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
